package com.example.fitnationprogress.enums;

public enum NotificationEventType {
    MEMBERSHIP_EXPIRING_SOON,
    MEMBERSHIP_REQUEST_SUBMITTED,
    MEMBERSHIP_REQUEST_APPROVED,
    MEMBERSHIP_REQUEST_REJECTED,
    MEMBERSHIP_PURCHASE_CONFIRMED,
    FREEZE_REQUEST_SUBMITTED,
    FREEZE_REQUEST_APPROVED,
    FREEZE_REQUEST_REJECTED,
    CLASS_BOOKED,
    CLASS_CANCELED,
    CLASS_FULL,
    TRAINER_ASSIGNMENT_REQUESTED,
    TRAINER_ASSIGNMENT_APPROVED,
    TRAINER_ASSIGNMENT_REJECTED
}
