spring:
  application:
    name: fitnation-rest-api
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  datasource:
    url: jdbc:postgresql://localhost:5432/fitnation
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
jwt:
  secret: fitnation-super-secret-key-must-be-at-least-32-characters-long
  expiration: 3600
  refresh-expiration: 604800